language: java

jdk:
  - oraclejdk8

before_script:
  - "mysql -e 'create database contact_manager;'"
  - "mysql -e 'create table contact_manager.contacts (id INT NOT NULL AUTO_INCREMENT, name VARCHAR(100), PRIMARY KEY(id));'"
  - "mysql -e 'INSERT INTO contact_manager.contacts (id, name) VALUES (1, 'Albert');'"

script: mvn install

after_failure:
  - "mysql -e 'show databases;'"
  - "cat ./config/database.yml"
  - "bundle exec rake --version"